export const Command = {
	KEYS: "KEYS",
	MEMBERS: "MEMBERS",
	ADD: "ADD",
	REMOVE: "REMOVE",
	REMOVEALL: "REMOVEALL",
	CLEAR: "CLEAR",
	KEYEXISTS: "KEYEXISTS",
	MEMBEREXISTS: "MEMBEREXISTS",
	ALLMEMBERS: "ALLMEMBERS",
	ITEMS: "ITEMS",
}
